import pygame

ImgTesoura = pygame.image.load('./img/tesoura.png').convert_alpha()
ImgTesoura_Escolhido = pygame.image.load('./img/tesoura_escolhido.png').convert_alpha()
ImgSair = pygame.image.load('./img/sair.png').convert_alpha()
ImgPedra = pygame.image.load('./img/pedra.png').convert_alpha()
ImgPedra_escolhido = pygame.image.load('./img/pedra_escolhido.png').convert_alpha()
ImgPapel = pygame.image.load('./img/papel.png').convert_alpha()
ImgPapel_escolhido = pygame.image.load('./img/papel_escolhido.png').convert_alpha()
ImgJogar = pygame.image.load('./img/jogar.png').convert_alpha()
ImgEscolhido = pygame.image.load('./img/escolhido.png').convert_alpha()
ImgCreditos = pygame.image.load('./img/creditos.png').convert_alpha()
ImgBG_home = pygame.image.load('./img/bg_home.png').convert_alpha()
ImgBG_game = pygame.image.load('./img/bg_game.png').convert_alpha()
ImgEsperando = pygame.image.load('./img/esperando.png').convert_alpha()
ImgNao = pygame.image.load('./img/nao_escolhido.png').convert_alpha()
ImgGanhou = pygame.image.load('./img/ganhou.png').convert_alpha()
ImgPerdeu = pygame.image.load('./img/perdeu.png').convert_alpha()
ImgEmpate = pygame.image.load('./img/empate.png').convert_alpha()